# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'TTMain' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for TTMain
  pod 'TTKit', :path => '../TTKit'
  pod 'TTServices', :path => '../TTServices'
  pod 'TTModules', :path => '../TTModules'
  target 'TTMainTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
